"""Generate summaries for Ontos documents.

This script reads document content and generates a 50-word summary
that can be stored in the frontmatter or displayed in the context map.

Note: This script requires an LLM to generate summaries. In v2.2,
summaries are generated by the AI agent during "Maintain Ontos".
"""

import os
import sys
import argparse
import re

from ontos_config import __version__, DOCS_DIR


def extract_content(filepath: str) -> str:
    """Extract markdown content (excluding frontmatter).
    
    Args:
        filepath: Path to markdown file.
        
    Returns:
        Content without YAML frontmatter.
    """
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    
    # Remove frontmatter
    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            return parts[2].strip()
    
    return content.strip()


def find_documents_needing_summary(docs_dir: str) -> list[tuple[str, str]]:
    """Find documents without summaries in frontmatter.
    
    Args:
        docs_dir: Documentation directory.
        
    Returns:
        List of (filepath, doc_id) tuples.
    """
    needs_summary = []
    
    for root, dirs, files in os.walk(docs_dir):
        for file in files:
            if not file.endswith('.md') or file.startswith('_'):
                continue
            
            filepath = os.path.join(root, file)
            
            with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
            
            if not content.startswith('---'):
                continue
            
            # Check if summary field exists
            if 'summary:' not in content.split('---')[1]:
                # Extract doc_id
                match = re.search(r'^id:\s*(\S+)', content, re.MULTILINE)
                if match:
                    doc_id = match.group(1)
                    # Skip logs (they don't need summaries)
                    if not doc_id.startswith('log_'):
                        needs_summary.append((filepath, doc_id))
    
    return needs_summary


def generate_summary_prompt(filepath: str, doc_id: str) -> str:
    """Generate a prompt for the AI to create a summary.
    
    Args:
        filepath: Path to the document.
        doc_id: Document ID.
        
    Returns:
        Prompt string.
    """
    content = extract_content(filepath)
    
    # Truncate very long content
    if len(content) > 5000:
        content = content[:5000] + "\n\n[Content truncated...]"
    
    return f"""Generate a 50-word summary for this document.

Document ID: {doc_id}
File: {filepath}

Content:
{content}

Requirements:
- Exactly 50 words (±5 words is acceptable)
- Focus on WHAT the document describes, not HOW
- Use present tense
- Start with a noun phrase (e.g., "Authentication flow for..." not "This document describes...")
- No markdown formatting in the summary

Output only the summary text, nothing else.
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate summaries for Ontos documents.',
        epilog="""
This script identifies documents without summaries and generates prompts
for AI-assisted summary creation.

Workflow:
1. Run this script to find documents needing summaries
2. For each document, the AI generates a 50-word summary
3. Add the summary to the document's frontmatter:
   
   ---
   id: my_doc
   type: atom
   summary: "50-word summary goes here..."
   ---
"""
    )
    parser.add_argument('--version', '-V', action='version', version=f'%(prog)s {__version__}')
    parser.add_argument('--dir', type=str, default=DOCS_DIR,
                        help=f'Documentation directory (default: {DOCS_DIR})')
    parser.add_argument('--file', type=str,
                        help='Generate prompt for a specific file')
    parser.add_argument('--quiet', '-q', action='store_true',
                        help='Suppress non-error output')
    args = parser.parse_args()
    
    if args.file:
        # Single file mode
        if not os.path.exists(args.file):
            print(f"Error: File not found: {args.file}")
            sys.exit(1)
        
        # Extract doc_id from file
        with open(args.file, 'r') as f:
            content = f.read()
        match = re.search(r'^id:\s*(\S+)', content, re.MULTILINE)
        doc_id = match.group(1) if match else os.path.basename(args.file)
        
        print(generate_summary_prompt(args.file, doc_id))
        return
    
    # Find all documents needing summaries
    needs_summary = find_documents_needing_summary(args.dir)
    
    if not needs_summary:
        if not args.quiet:
            print("✅ All documents have summaries.")
        return
    
    if not args.quiet:
        print(f"Found {len(needs_summary)} document(s) without summaries:\n")
        for filepath, doc_id in needs_summary:
            print(f"  - {doc_id} ({os.path.basename(filepath)})")
        
        print()
        print("To generate summaries, run for each file:")
        print("  python3 .ontos/scripts/ontos_summarize.py --file <filepath>")
        print()
        print("Or ask your AI agent: 'Generate summaries for documents missing them'")


if __name__ == "__main__":
    main()
