# AGENTS.md

This project uses **Ontos** for documentation management.

Generated by Ontos v3.0.0 on 2026-01-17 12:52:53 UTC

## Ontos Activation
1. Run `ontos map` to regenerate the context map.
2. Read `Ontos_Context_Map.md` to understand the documentation graph.
3. Load only the relevant documents for the task.
4. Follow `depends_on` upward as needed.
5. Confirm: "Loaded: [ids]".

## Session End
1. Run `ontos log -e "slug"` to archive session work.
2. Fill in Goal, Key Decisions, Alternatives Considered, and Impacts.

## Quick Reference
| Command | Purpose |
|---------|---------|
| `ontos map` | Regenerate context map |
| `ontos agents` | Generate instruction files |
| `ontos doctor` | Health check and validation |
| `ontos log -e "slug"` | Archive session work |
| `ontos query <id>` | Find document by ID |

## Project Stats
- Doc Count: 5
- Last Updated: 2026-01-17 12:52:36 UTC

## Core Invariants
- Do not edit `Ontos_Context_Map.md` manually; regenerate with `ontos map`.
- Do not edit `AGENTS.md` manually; regenerate with `ontos agents`.
- If a command fails, read the error message and avoid guessing fixes.

## Staleness
If `AGENTS.md` is older than the context map or logs, regenerate with `ontos agents`.
