# ontos/commands/agents.py
"""
AGENTS.md and .cursorrules generation command.

Generates AI assistant integration files per Spec v1.1.
"""

import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional, Tuple

import ontos
from ontos.commands.instruction_protocol import (
    InstructionProtocolConfig,
    preserve_user_custom_section,
    render_activation_protocol_head,
    render_activation_protocol_tail,
    render_trigger_phrases,
)


@dataclass
class AgentsOptions:
    """Configuration for agents command."""
    output_path: Optional[Path] = None
    force: bool = False
    format: str = "agents"  # agents|cursor
    all_formats: bool = False
    scope: Optional[str] = None


AGENTS_PROTOCOL_CONFIG = InstructionProtocolConfig(
    instruction_file="AGENTS.md",
    regenerate_command="ontos agents",
    regenerate_purpose="Generate instruction files",
    staleness_command="ontos map --sync-agents",
    map_sync_command="ontos map --sync-agents",
    map_sync_purpose="Regenerate map + sync AGENTS.md",
)

AGENTS_HEADER_TEMPLATE = """# AGENTS.md

This project uses **Ontos** for documentation management.

Generated by Ontos v{ontos_version} on {generated_at}"""

AGENTS_CURRENT_PROJECT_STATE_TEMPLATE = """## Current Project State

> Auto-synced: {generated_at}

| Metric | Value |
|--------|-------|
| Branch | {current_branch} |
| Doc Count | {doc_count} |
| Last Log | {last_log} |
| Health | {health_summary} |"""

AGENTS_PROJECT_STATS_TEMPLATE = """## Project Stats
- Doc Count: {doc_count}
- Last Updated: {last_updated}"""


def find_repo_root() -> Optional[Path]:
    """
    Find the repository root using 3-method fallback.
    
    1. Find .ontos.toml in current or parent dirs
    2. Use git rev-parse --show-toplevel
    3. Fall back to .git directory walk
    
    Returns:
        Path to repo root, or None if no repository found.
    """
    current = Path.cwd()
    
    # Method 1: Look for .ontos.toml
    for parent in [current] + list(current.parents):
        if (parent / ".ontos.toml").exists():
            return parent
    
    # Method 2: Try git rev-parse
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    
    # Method 3: Look for .git
    for parent in [current] + list(current.parents):
        if (parent / ".git").exists():
            return parent
    
    # No repo found - return None instead of cwd to prevent arbitrary writes
    return None


def gather_stats(repo_root: Path, scope: Optional[str] = None) -> Dict[str, str]:
    """
    Gather project stats for template.

    Returns:
        Dict with keys: doc_count, last_updated, current_branch, last_log, health_summary
    """
    stats = {
        "doc_count": "Unknown",
        "last_updated": "Unknown",
        "current_branch": "Unknown",
        "last_log": "None",
        "health_summary": "Unknown",
    }

    try:
        # Load config to find docs and logs directories.
        config_path = repo_root / ".ontos.toml"
        docs_dir = repo_root / "docs"
        logs_dir = repo_root / "docs" / "logs"
        context_map = repo_root / "Ontos_Context_Map.md"

        skip_patterns = []
        if config_path.exists():
            try:
                from ontos.io.config import load_project_config
                from ontos.io.scan_scope import collect_scoped_documents, resolve_scan_scope

                config = load_project_config(repo_root=repo_root)
                docs_dir = repo_root / config.paths.docs_dir
                logs_dir = repo_root / config.paths.logs_dir
                context_map = repo_root / config.paths.context_map
                skip_patterns = config.scanning.skip_patterns

                effective_scope = resolve_scan_scope(scope, config.scanning.default_scope)
                doc_paths = collect_scoped_documents(
                    repo_root,
                    config,
                    effective_scope,
                    base_skip_patterns=skip_patterns,
                )
            except Exception:
                doc_paths = []
        else:
            doc_paths = []

        if not doc_paths and docs_dir.exists():
            # Fallback for repos without config (legacy behavior).
            from ontos.io.files import scan_documents
            doc_paths = scan_documents([docs_dir], skip_patterns=skip_patterns)
        count = len(doc_paths)
        if count >= 5000:
            stats["doc_count"] = "5000+"
        else:
            stats["doc_count"] = str(count)

        # Find max mtime
        mtimes = []
        for path in [context_map, config_path]:
            if path.exists():
                mtimes.append(path.stat().st_mtime)

        if logs_dir.exists():
            for log_file in logs_dir.glob("*.md"):
                mtimes.append(log_file.stat().st_mtime)

        if mtimes:
            max_mtime = max(mtimes)
            dt = datetime.fromtimestamp(max_mtime, tz=timezone.utc)
            stats["last_updated"] = dt.strftime("%Y-%m-%d %H:%M:%S UTC")

        # Get current git branch
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=repo_root
            )
            if result.returncode == 0:
                stats["current_branch"] = result.stdout.strip()
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

        # Get most recent log (by filename, assumes YYYY-MM-DD prefix)
        if logs_dir.exists():
            log_files = sorted(logs_dir.glob("*.md"), reverse=True)
            if log_files:
                stats["last_log"] = log_files[0].stem

        # Get health summary (simple version - just check if context map exists)
        if context_map.exists():
            stats["health_summary"] = "✓ Map exists"
        else:
            stats["health_summary"] = "⚠ No map"

    except Exception:
        pass  # Keep defaults on any error

    return stats


def generate_agents_content(existing_content: Optional[str] = None, scope: Optional[str] = None) -> str:
    """Generate AGENTS.md content with stats."""
    repo_root = find_repo_root()
    stats = gather_stats(repo_root, scope=scope)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header = AGENTS_HEADER_TEMPLATE.format(
        ontos_version=ontos.__version__,
        generated_at=generated_at,
    )

    current_project_state = AGENTS_CURRENT_PROJECT_STATE_TEMPLATE.format(
        generated_at=generated_at,
        current_branch=stats["current_branch"],
        doc_count=stats["doc_count"],
        last_log=stats["last_log"],
        health_summary=stats["health_summary"],
    )

    trigger_phrases = render_trigger_phrases()
    activation_head = render_activation_protocol_head(AGENTS_PROTOCOL_CONFIG)
    project_stats = AGENTS_PROJECT_STATS_TEMPLATE.format(
        doc_count=stats["doc_count"],
        last_updated=stats["last_updated"],
    )
    activation_tail = render_activation_protocol_tail(AGENTS_PROTOCOL_CONFIG)

    content = "\n\n".join([
        header,
        trigger_phrases,
        current_project_state,
        activation_head,
        project_stats,
        activation_tail,
    ]) + "\n"

    return preserve_user_custom_section(content, existing_content)


def transform_to_cursorrules(agents_content: str) -> str:
    """
    Transform AGENTS.md content to .cursorrules format.
    
    Per Appendix B transform rules.
    """
    lines = agents_content.split('\n')
    result = []
    
    in_section = None
    skip_until_next_section = False
    
    for line in lines:
        # Title replacement
        if line.startswith('# AGENTS.md'):
            result.append('# Ontos Protocol for Cursor')
            continue
        
        # Section detection
        if line.startswith('## '):
            section_name = line[3:].strip()
            skip_until_next_section = False
            
            if section_name == 'Ontos Activation':
                result.append('')
                result.append('When the user says "Ontos" or "Activate Ontos":')
                result.append('')
                result.append('## Activation')
                in_section = 'activation'
                continue
            elif section_name == 'Session End':
                result.append('')
                result.append('When ending a session:')
                result.append('')
                result.append('## Session End')
                in_section = 'session_end'
                continue
            elif section_name in (
                'Trigger Phrases',
                'Re-Activation Trigger',
                'After Context Compaction (/compact)',
                'Quick Reference',
                'Project Stats',
                'Core Invariants',
                'Staleness',
            ):
                result.append(line)
                in_section = section_name.lower().replace(' ', '_')
                continue
            else:
                # Remove unknown sections
                skip_until_next_section = True
                in_section = None
                continue
        
        if skip_until_next_section:
            continue
        
        result.append(line)
    
    return '\n'.join(result)


def create_backup(path: Path) -> None:
    """Create .bak backup of existing file."""
    if path.exists():
        backup_path = path.with_suffix(path.suffix + '.bak')
        backup_path.write_text(path.read_text(encoding='utf-8'), encoding='utf-8')


def agents_command(options: AgentsOptions) -> Tuple[int, str]:
    """
    Generate AGENTS.md and/or .cursorrules files.
    
    Returns:
        Tuple of (exit_code, message)
    
    Exit Codes:
        0: Success
        1: File exists (use --force)
        2: Configuration error
    """
    repo_root = find_repo_root()
    if repo_root is None:
        return 2, "Error: No repository found. Run from within a git repository or Ontos project."
    
    messages = []
    
    # Determine what to generate
    generate_agents = options.format == "agents" or options.all_formats
    generate_cursor = options.format == "cursor" or options.all_formats
    
    # Generate AGENTS.md
    if generate_agents:
        agents_path = options.output_path or repo_root / "AGENTS.md"
        
        # Path safety validation
        try:
            resolved_output = agents_path.resolve()
            resolved_root = repo_root.resolve()
            resolved_output.relative_to(resolved_root)
        except ValueError:
            return 2, f"Error: Output path must be within repository root ({repo_root})"
        
        if agents_path.exists() and not options.force:
            return 1, f"AGENTS.md already exists at {agents_path}. Use --force to overwrite."
        
        try:
            if options.force and agents_path.exists():
                create_backup(agents_path)
            
            existing_content = None
            if agents_path.exists():
                existing_content = agents_path.read_text(encoding='utf-8')
                
            agents_path.parent.mkdir(parents=True, exist_ok=True)
            content = generate_agents_content(existing_content, scope=options.scope)
            agents_path.write_text(content, encoding='utf-8')
            messages.append(f"Created {agents_path}")
        except Exception as e:
            return 2, f"Error writing AGENTS.md: {e}"
    
    # Generate .cursorrules
    if generate_cursor:
        cursor_path = repo_root / ".cursorrules"
        
        if cursor_path.exists() and not options.force:
            if generate_agents:
                # Already created AGENTS, warn about cursor
                messages.append(f".cursorrules already exists. Use --force to overwrite.")
            else:
                return 1, f".cursorrules already exists at {cursor_path}. Use --force to overwrite."
        else:
            try:
                if options.force and cursor_path.exists():
                    create_backup(cursor_path)
                
                # Check for existing AGENTS.md content to pass through
                existing_agents_path = repo_root / "AGENTS.md"
                existing_content = None
                if existing_agents_path.exists():
                    existing_content = existing_agents_path.read_text(encoding='utf-8')
                
                agents_content = generate_agents_content(existing_content, scope=options.scope)
                cursor_content = transform_to_cursorrules(agents_content)
                cursor_path.write_text(cursor_content, encoding='utf-8')
                messages.append(f"Created {cursor_path}")
            except Exception as e:
                return 2, f"Error writing .cursorrules: {e}"
    
    return 0, '\n'.join(messages) if messages else "No files generated"
