"""(#173 slice-A) Instruction-file ownership classification and
content-based staleness."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from ontos.core.instruction_artifacts import (
    OWNERSHIP_MANAGED_BLOCK,
    OWNERSHIP_MISSING,
    OWNERSHIP_ONTOS_OWNED,
    OWNERSHIP_USER_MANAGED,
    classify_instruction_ownership,
    generate_agents_content,
    is_agents_semantically_stale,
)


class TestClassifyInstructionOwnership:
    def test_missing_file(self, tmp_path):
        assert classify_instruction_ownership(tmp_path / "AGENTS.md") == OWNERSHIP_MISSING

    def test_generated_file_is_ontos_owned(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")
        assert classify_instruction_ownership(path) == OWNERSHIP_ONTOS_OWNED

    def test_header_in_fixed_position_is_ontos_owned(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# AGENTS.md\n\nThis project uses **Ontos** for documentation management.\n\n"
            "Generated by Ontos v5.0.2 on 2026-07-01 00:00:00 UTC\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_ONTOS_OWNED

    def test_user_custom_markers_without_header_is_managed_block(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# Mine\n<!-- USER CUSTOM -->x<!-- /USER CUSTOM -->\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_MANAGED_BLOCK

    def test_plain_file_is_user_managed(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text("# My own agent instructions\n")
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_quoted_header_mid_file_does_not_confer_ownership(self, tmp_path):
        # PR #182 review P1: the phrase appearing as an example inside a
        # hand-authored file must not classify the file as Ontos-owned.
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# My handbook\n\nSome rules.\nMore rules.\nEven more.\n"
            "And more.\nStill more.\nYet more.\n\n"
            "Example of what ontos writes:\n\n"
            "Generated by Ontos v5.0.2 on 2026-01-01 00:00:00 UTC\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_indented_header_in_head_does_not_confer_ownership(self, tmp_path):
        # A quoted/indented example in the head region is not the fixed-
        # position unindented header line.
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# Mine\n\n    Generated by Ontos v5.0.2 on 2026-01-01 00:00:00 UTC\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_partial_header_phrase_does_not_confer_ownership(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text("Generated by Ontos v5 without the timestamp part\n")
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_quoted_header_after_user_prose_in_head_stays_user_managed(self, tmp_path):
        # PR #182 review reproduction: header phrase quoted as an example
        # near the top of a hand-authored file. User prose precedes it, so
        # structural validation must reject ownership.
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# My handbook\n\nExample of what ontos writes:\n\n"
            "Generated by Ontos v5.0.2 on 2026-01-01 00:00:00 UTC\n\n"
            "My own rules here.\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_unreadable_bytes_fail_closed_to_user_managed(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_bytes(b"\xff\xfe\x00ridiculous\x00")
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED


class TestSemanticStaleness:
    def test_fresh_content_is_not_stale(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")

        assert is_agents_semantically_stale(tmp_path) is False

    def test_project_state_drift_is_stale(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")

        docs = tmp_path / "docs"
        docs.mkdir()
        (docs / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")

        assert is_agents_semantically_stale(tmp_path) is True

    def test_clone_agrees_with_source_checkout(self, tmp_path, monkeypatch):
        """(#173) The reproduced failure: a fresh git clone of an up-to-date
        repo must not flip the staleness verdict via checkout write order."""
        def _git(*args, cwd):
            subprocess.run(
                ["git", "-c", "user.email=t@example.test", "-c", "user.name=T", *args],
                cwd=cwd,
                check=True,
                capture_output=True,
            )

        src = tmp_path / "src"
        src.mkdir()
        monkeypatch.chdir(src)
        # A resolvable HEAD must exist BEFORE generation: the branch name is
        # part of the generated stats, so it has to match between src and
        # clone (an unborn branch reports "Unknown").
        _git("init", "--initial-branch=main", cwd=src)
        (src / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        docs = src / "docs"
        (docs / "logs").mkdir(parents=True)
        (docs / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")
        (docs / "logs" / "2026-01-01_x.md").write_text("# log\n")
        _git("add", ".", cwd=src)
        _git("commit", "-m", "initial", cwd=src)

        (src / "AGENTS.md").write_text(generate_agents_content(), encoding="utf-8")

        assert is_agents_semantically_stale(src) is False

        _git("add", ".", cwd=src)
        _git("commit", "-m", "add agents", cwd=src)
        clone = tmp_path / "clone"
        _git("clone", str(src), str(clone), cwd=tmp_path)

        monkeypatch.chdir(clone)
        assert is_agents_semantically_stale(clone) is False

    def test_worktree_on_different_branch_is_not_stale(self, tmp_path, monkeypatch):
        """PR #182 review P1: at identical HEAD, a feature-branch worktree
        must agree with the original branch on freshness — the branch is
        checkout-local state, not project content."""

        def _git(*args, cwd):
            subprocess.run(
                ["git", "-c", "user.email=t@example.test", "-c", "user.name=T", *args],
                cwd=cwd,
                check=True,
                capture_output=True,
            )

        repo = tmp_path / "repo"
        repo.mkdir()
        monkeypatch.chdir(repo)
        _git("init", "--initial-branch=main", cwd=repo)
        (repo / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        docs = repo / "docs"
        docs.mkdir()
        (docs / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")
        _git("add", ".", cwd=repo)
        _git("commit", "-m", "initial", cwd=repo)

        (repo / "AGENTS.md").write_text(generate_agents_content(), encoding="utf-8")
        _git("add", ".", cwd=repo)
        _git("commit", "-m", "agents", cwd=repo)
        assert is_agents_semantically_stale(repo) is False

        worktree = tmp_path / "wt-feature"
        _git("worktree", "add", "-b", "feature", str(worktree), cwd=repo)
        monkeypatch.chdir(worktree)
        assert is_agents_semantically_stale(worktree) is False

    def test_staleness_uses_passed_root_not_cwd(self, tmp_path, monkeypatch):
        """PR #182 review P1: freshness must be computed against the passed
        repository root, not whatever repository the process happens to be
        running in."""
        repo_a = tmp_path / "repo_a"
        repo_a.mkdir()
        monkeypatch.chdir(repo_a)
        (repo_a / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        docs_a = repo_a / "docs"
        docs_a.mkdir()
        (docs_a / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")
        (repo_a / "AGENTS.md").write_text(generate_agents_content(), encoding="utf-8")
        assert is_agents_semantically_stale(repo_a) is False

        # A second repository with a very different doc population.
        repo_b = tmp_path / "repo_b"
        repo_b.mkdir()
        (repo_b / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        docs_b = repo_b / "docs"
        docs_b.mkdir()
        for i in range(5):
            (docs_b / f"b{i}.md").write_text(
                f"---\nid: b{i}\ntype: atom\nstatus: active\n---\n"
            )

        # CWD in repo_b must not poison the verdict for repo_a.
        monkeypatch.chdir(repo_b)
        assert is_agents_semantically_stale(repo_a) is False
