"""(#173 slice-A) Instruction-file ownership classification and
content-based staleness."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from ontos.core.instruction_artifacts import (
    OWNERSHIP_MANAGED_BLOCK,
    OWNERSHIP_MISSING,
    OWNERSHIP_ONTOS_OWNED,
    OWNERSHIP_USER_MANAGED,
    classify_instruction_ownership,
    generate_agents_content,
    is_agents_semantically_stale,
)


class TestClassifyInstructionOwnership:
    def test_missing_file(self, tmp_path):
        assert classify_instruction_ownership(tmp_path / "AGENTS.md") == OWNERSHIP_MISSING

    def test_generated_file_is_ontos_owned(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")
        assert classify_instruction_ownership(path) == OWNERSHIP_ONTOS_OWNED

    def test_header_alone_is_ontos_owned(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# AGENTS.md\n\nGenerated by Ontos v5.0.2 on 2026-07-01 00:00:00 UTC\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_ONTOS_OWNED

    def test_user_custom_markers_without_header_is_managed_block(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text(
            "# Mine\n<!-- USER CUSTOM -->x<!-- /USER CUSTOM -->\n"
        )
        assert classify_instruction_ownership(path) == OWNERSHIP_MANAGED_BLOCK

    def test_plain_file_is_user_managed(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text("# My own agent instructions\n")
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED

    def test_unreadable_bytes_fail_closed_to_user_managed(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_bytes(b"\xff\xfe\x00ridiculous\x00")
        assert classify_instruction_ownership(path) == OWNERSHIP_USER_MANAGED


class TestSemanticStaleness:
    def test_fresh_content_is_not_stale(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")

        assert is_agents_semantically_stale(tmp_path) is False

    def test_project_state_drift_is_stale(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        path = tmp_path / "AGENTS.md"
        path.write_text(generate_agents_content(), encoding="utf-8")

        docs = tmp_path / "docs"
        docs.mkdir()
        (docs / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")

        assert is_agents_semantically_stale(tmp_path) is True

    def test_clone_agrees_with_source_checkout(self, tmp_path, monkeypatch):
        """(#173) The reproduced failure: a fresh git clone of an up-to-date
        repo must not flip the staleness verdict via checkout write order."""
        def _git(*args, cwd):
            subprocess.run(
                ["git", "-c", "user.email=t@example.test", "-c", "user.name=T", *args],
                cwd=cwd,
                check=True,
                capture_output=True,
            )

        src = tmp_path / "src"
        src.mkdir()
        monkeypatch.chdir(src)
        # A resolvable HEAD must exist BEFORE generation: the branch name is
        # part of the generated stats, so it has to match between src and
        # clone (an unborn branch reports "Unknown").
        _git("init", "--initial-branch=main", cwd=src)
        (src / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n")
        docs = src / "docs"
        (docs / "logs").mkdir(parents=True)
        (docs / "a.md").write_text("---\nid: a\ntype: atom\nstatus: active\n---\n")
        (docs / "logs" / "2026-01-01_x.md").write_text("# log\n")
        _git("add", ".", cwd=src)
        _git("commit", "-m", "initial", cwd=src)

        (src / "AGENTS.md").write_text(generate_agents_content(), encoding="utf-8")

        assert is_agents_semantically_stale(src) is False

        _git("add", ".", cwd=src)
        _git("commit", "-m", "add agents", cwd=src)
        clone = tmp_path / "clone"
        _git("clone", str(src), str(clone), cwd=tmp_path)

        monkeypatch.chdir(clone)
        assert is_agents_semantically_stale(clone) is False
