"""Ontos default configuration constants.

This file contains the default configuration shipped with Ontos.
DO NOT EDIT THIS FILE - it will be overwritten by ontos_update.py.

To customize settings, override them in ontos_config.py instead.
"""

import os

# Project root detection
# Assumes this file is in .ontos/scripts/ relative to project root
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def is_ontos_repo() -> bool:
    """Check if this is the Ontos repository itself (contributor mode).
    
    Returns:
        True if .ontos-internal/ exists (contributor mode),
        False otherwise (user mode).
    """
    return os.path.exists(os.path.join(PROJECT_ROOT, '.ontos-internal'))

# Version - used by update script to check for newer versions
ONTOS_VERSION = "2.9.0"

# GitHub repository for updates
ONTOS_REPO_URL = 'https://github.com/ohjona/project-ontos'
ONTOS_REPO_RAW_URL = 'https://raw.githubusercontent.com/ohjona/project-ontos/main'

# Directory settings (defaults - override in ontos_config.py)
DEFAULT_DOCS_DIR = 'docs'
DEFAULT_LOGS_DIR = 'docs/logs'

# Output files
DEFAULT_CONTEXT_MAP_FILE = 'Ontos_Context_Map.md'
DEFAULT_MIGRATION_PROMPT_FILE = 'migration_prompt.txt'

# Validation thresholds
DEFAULT_MAX_DEPENDENCY_DEPTH = 5

# Document type definitions (single source of truth)
TYPE_DEFINITIONS = {
    # --- SPACE ONTOLOGY (Truth) ---
    # These document what IS true about the project
    'kernel': {
        'rank': 0,
        'description': 'Core identity documents (mission, principles)',
        'allows_depends_on': True,
    },
    'strategy': {
        'rank': 1,
        'description': 'High-level direction and decisions',
        'allows_depends_on': True,
    },
    'product': {
        'rank': 2,
        'description': 'Feature specifications and requirements',
        'allows_depends_on': True,
    },
    'atom': {
        'rank': 3,
        'description': 'Implementation details and technical specs',
        'allows_depends_on': True,
    },
    # --- TIME ONTOLOGY (History) ---
    # These document what HAPPENED during development
    'log': {
        'rank': 4,
        'description': 'Session history (what happened, not what is)',
        'allows_depends_on': False,  # Logs use 'impacts' instead
    },
}

# Valid types for early validation
VALID_TYPES = set(TYPE_DEFINITIONS.keys())

# Derived hierarchy for backward compatibility
TYPE_HIERARCHY = {k: v['rank'] for k, v in TYPE_DEFINITIONS.items()}


# =============================================================================
# EVENT TYPES (v2.0+)
# =============================================================================
# Captures the PRIMARY intent of a development session
# Used in log documents to categorize work

EVENT_TYPES = {
    'feature': {
        'definition': 'Adding new capability to the system',
        'examples': ['Implemented OAuth login', 'Added search functionality'],
    },
    'fix': {
        'definition': 'Correcting broken or incorrect behavior',
        'examples': ['Fixed refresh token bug', 'Resolved race condition'],
    },
    'refactor': {
        'definition': 'Restructuring code without changing behavior',
        'examples': ['Split auth module', 'Migrated to TypeScript'],
    },
    'exploration': {
        'definition': 'Research, spikes, or prototypes',
        'examples': ['Evaluated database options', 'Tested new library'],
    },
    'chore': {
        'definition': 'Maintenance, dependencies, configuration',
        'examples': ['Updated dependencies', 'Fixed CI pipeline'],
    },
    'decision': {  # NEW
        'definition': 'Architectural or design decisions',
        'examples': ['Chose OAuth over SAML', 'Selected PostgreSQL for persistence'],
    },
}

# Valid event type values (for validation)
VALID_EVENT_TYPES = set(EVENT_TYPES.keys())


# =============================================================================
# STATUS VALUES (v2.6+)
# =============================================================================
# Valid status values for document frontmatter

VALID_STATUS = {'draft', 'active', 'deprecated', 'archived', 'rejected', 'complete'}

# Status descriptions - clarifying archived vs rejected
STATUS_DEFINITIONS = {
    'draft': 'Work in progress (proposals, incomplete docs)',
    'active': 'Current truth (approved, in use)',
    'deprecated': 'Past truth (superseded, kept for reference)',
    'archived': 'Historical record (completed logs moved to archive)',
    'rejected': 'Considered but NOT approved (proposals only - never became truth)',
    'complete': 'Finished work (reviews, completed tasks)',
}

# Valid (type, status) combinations - prevents semantic nonsense
# Example: type: log cannot have status: rejected (logs record what happened)
VALID_TYPE_STATUS = {
    'kernel': {'active', 'draft', 'deprecated'},
    'strategy': {'active', 'draft', 'deprecated', 'rejected', 'complete'},  # Reviews can be complete
    'product': {'active', 'draft', 'deprecated'},
    'atom': {'active', 'draft', 'deprecated', 'complete'},  # Reviews can be complete
    'log': {'active', 'archived'},  # Logs cannot be draft or rejected
}

# Stale proposal detection threshold (days)
PROPOSAL_STALE_DAYS = 60

# Minimum characters for rejection reason (prevents useless reasons like "No")
REJECTED_REASON_MIN_LENGTH = 10


# Types that are allowed to be orphans (no dependents)
DEFAULT_ALLOWED_ORPHAN_TYPES = ['product', 'strategy', 'kernel']

# Files/patterns to skip during scanning (defaults)
# - _template.md: Template files
# - Ontos_: Ontos tooling files (Agent Instructions, Manual, Guides, etc.)
DEFAULT_SKIP_PATTERNS = ['_template.md', 'Ontos_', '.ontos-internal/']

# Patterns to skip when scanning docs (v2.3+)
SKIP_PATTERNS = [
    'archive/',
    'Ontos_CHANGELOG.md',
    'README.md',
    '.git/',
    'node_modules/',
    '__pycache__/',
]


# =============================================================================
# WORKFLOW ENFORCEMENT (v2.0+)
# =============================================================================
# These settings control how strictly Ontos enforces workflow rules.
# Override in ontos_config.py to customize for your project.
#
# Strict mode (defaults): Best for teams, ensures context is always captured
# Relaxed mode: Better for solo devs, rapid prototyping, or learning Ontos

# Pre-push hook behavior
# - True (default): BLOCK push until session is archived (recommended for teams)
# - False: Advisory only - show reminder but allow push
ENFORCE_ARCHIVE_BEFORE_PUSH = True

# Session log authorship tracking
# - True (default): --source flag is REQUIRED in ontos_end_session.py
# - False: --source is optional (logs may lack attribution)
REQUIRE_SOURCE_IN_LOGS = True

# =============================================================================
# MEMORY MANAGEMENT (v2.1+)
# =============================================================================
# Controls the "Working Memory" size - how many logs stay in active scanning.
# Logs beyond this threshold should be consolidated and archived.

# Recommended threshold for active logs before consolidation
# - Lower = smaller context maps, more frequent consolidation
# - Higher = more history in context, less consolidation overhead
LOG_RETENTION_COUNT = 15

# =============================================================================
# UX IMPROVEMENTS (v2.3+)
# =============================================================================

# Small change threshold (lines) for pre-push hook
# Changes below this get softer "skip this time" message
SMALL_CHANGE_THRESHOLD = 20

# Default source for session logs (set in ontos_config.py)
# Example: DEFAULT_SOURCE = "Claude Code"
DEFAULT_SOURCE = None

# =============================================================================
# MODE SYSTEM (v2.4+)
# =============================================================================
# Three modes to control workflow friction:
# - "automated": Zero friction, auto-archives on push, best for solo devs
# - "prompted": Blocked until archived, you control details (default for new installs)
# - "advisory": Reminders only, maximum flexibility
#
# Set ONTOS_MODE in ontos_config.py. Individual settings can override mode defaults.

# Current mode (set in ontos_config.py, defaults to None = legacy behavior)
ONTOS_MODE = None

# Mode preset configurations
MODE_PRESETS = {
    'automated': {
        'AUTO_ARCHIVE_ON_PUSH': True,
        'ENFORCE_ARCHIVE_BEFORE_PUSH': False,
        'REQUIRE_SOURCE_IN_LOGS': False,
        'AUTO_CONSOLIDATE': True,
        'AUTO_CONSOLIDATE_ON_COMMIT': True,  # v2.5: Pre-commit hook consolidation
    },
    'prompted': {
        'AUTO_ARCHIVE_ON_PUSH': False,
        'ENFORCE_ARCHIVE_BEFORE_PUSH': True,
        'REQUIRE_SOURCE_IN_LOGS': True,
        'AUTO_CONSOLIDATE': True,
        'AUTO_CONSOLIDATE_ON_COMMIT': False,  # v2.5: Manual consolidation, agent reminder
    },
    'advisory': {
        'AUTO_ARCHIVE_ON_PUSH': False,
        'ENFORCE_ARCHIVE_BEFORE_PUSH': False,
        'REQUIRE_SOURCE_IN_LOGS': False,
        'AUTO_CONSOLIDATE': False,
        'AUTO_CONSOLIDATE_ON_COMMIT': False,  # v2.5: Manual consolidation only
    },
}

# Valid mode values (for validation)
VALID_MODES = set(MODE_PRESETS.keys())

# Auto-archive on push (v2.4+)
# - True: Auto-create session log on git push (automated mode)
# - False: Manual archive required (prompted/advisory modes)
AUTO_ARCHIVE_ON_PUSH = False

# Auto-consolidate in Maintain Ontos (v2.4+)
# - True: Maintenance automatically consolidates old logs
# - False: Manual consolidation only
AUTO_CONSOLIDATE = True

# Auto-consolidate on commit (v2.5+)
# - True: Pre-commit hook consolidates old logs automatically
# - False: Manual consolidation only (or agent reminder in prompted mode)
# Only applies to 'automated' mode by default
AUTO_CONSOLIDATE_ON_COMMIT = False

# Hook timeout to prevent slow hooks from frustrating users (v2.4+)
# Operations in pre-push hook will timeout after this many seconds
HOOK_TIMEOUT_SECONDS = 10

# Consolidation threshold for maintenance (v2.4+)
# Logs older than this many days are candidates for consolidation
CONSOLIDATION_THRESHOLD_DAYS = 30
