"""Ontos default configuration constants.

This file contains the default configuration shipped with Ontos.
DO NOT EDIT THIS FILE - it will be overwritten by ontos_update.py.

To customize settings, override them in ontos_config.py instead.
"""

# Version - used by update script to check for newer versions
ONTOS_VERSION = '2.0.0'

# GitHub repository for updates
ONTOS_REPO_URL = 'https://github.com/ohjona/project-ontos'
ONTOS_REPO_RAW_URL = 'https://raw.githubusercontent.com/ohjona/project-ontos/main'

# Directory settings (defaults - override in ontos_config.py)
DEFAULT_DOCS_DIR = 'docs'
DEFAULT_LOGS_DIR = 'docs/logs'

# Output files
DEFAULT_CONTEXT_MAP_FILE = 'Ontos_Context_Map.md'
DEFAULT_MIGRATION_PROMPT_FILE = 'migration_prompt.txt'

# Validation thresholds
DEFAULT_MAX_DEPENDENCY_DEPTH = 5

# Document type definitions (single source of truth)
TYPE_DEFINITIONS = {
    # --- SPACE ONTOLOGY (Truth) ---
    # These document what IS true about the project
    'kernel': {
        'rank': 0,
        'description': 'Core identity documents (mission, principles)',
        'allows_depends_on': True,
    },
    'strategy': {
        'rank': 1,
        'description': 'High-level direction and decisions',
        'allows_depends_on': True,
    },
    'product': {
        'rank': 2,
        'description': 'Feature specifications and requirements',
        'allows_depends_on': True,
    },
    'atom': {
        'rank': 3,
        'description': 'Implementation details and technical specs',
        'allows_depends_on': True,
    },
    # --- TIME ONTOLOGY (History) ---
    # These document what HAPPENED during development
    'log': {
        'rank': 4,
        'description': 'Session history (what happened, not what is)',
        'allows_depends_on': False,  # Logs use 'impacts' instead
    },
}

# Valid types for early validation
VALID_TYPES = set(TYPE_DEFINITIONS.keys())

# Derived hierarchy for backward compatibility
TYPE_HIERARCHY = {k: v['rank'] for k, v in TYPE_DEFINITIONS.items()}


# =============================================================================
# EVENT TYPES (v2.0+)
# =============================================================================
# Captures the PRIMARY intent of a development session
# Used in log documents to categorize work

EVENT_TYPES = {
    'feature': {
        'definition': 'Adding new capability to the system',
        'examples': ['Implemented OAuth login', 'Added search functionality'],
    },
    'fix': {
        'definition': 'Correcting broken or incorrect behavior',
        'examples': ['Fixed refresh token bug', 'Resolved race condition'],
    },
    'refactor': {
        'definition': 'Restructuring code without changing behavior',
        'examples': ['Split auth module', 'Migrated to TypeScript'],
    },
    'exploration': {
        'definition': 'Research, spikes, or prototypes',
        'examples': ['Evaluated database options', 'Tested new library'],
    },
    'chore': {
        'definition': 'Maintenance, dependencies, configuration',
        'examples': ['Updated dependencies', 'Fixed CI pipeline'],
    },
}

# Valid event type values (for validation)
VALID_EVENT_TYPES = set(EVENT_TYPES.keys())

# Types that are allowed to be orphans (no dependents)
DEFAULT_ALLOWED_ORPHAN_TYPES = ['product', 'strategy', 'kernel']

# Files/patterns to skip during scanning (defaults)
# - _template.md: Template files
# - Ontos_: Ontos tooling files (Agent Instructions, Manual, Guides, etc.)
DEFAULT_SKIP_PATTERNS = ['_template.md', 'Ontos_', '.ontos-internal/']


# =============================================================================
# WORKFLOW ENFORCEMENT (v2.0+)
# =============================================================================
# These settings control how strictly Ontos enforces workflow rules.
# Override in ontos_config.py to customize for your project.
#
# Strict mode (defaults): Best for teams, ensures context is always captured
# Relaxed mode: Better for solo devs, rapid prototyping, or learning Ontos

# Pre-push hook behavior
# - True (default): BLOCK push until session is archived (recommended for teams)
# - False: Advisory only - show reminder but allow push
ENFORCE_ARCHIVE_BEFORE_PUSH = True

# Session log authorship tracking
# - True (default): --source flag is REQUIRED in ontos_end_session.py
# - False: --source is optional (logs may lack attribution)
REQUIRE_SOURCE_IN_LOGS = True
