"""Tests for agents command."""

from pathlib import Path
from datetime import datetime

import pytest

from ontos.commands.agents import (
    AgentsOptions,
    agents_command,
    find_repo_root,
    _get_project_name,
    _get_doc_count,
    _generate_agents_md,
    _generate_cursorrules,
)


class TestAgentsOptions:
    """Tests for AgentsOptions dataclass."""

    def test_default_values(self):
        options = AgentsOptions()
        assert options.format == "agents"
        assert options.output_path is None
        assert options.force is False

    def test_with_values(self):
        options = AgentsOptions(
            format="cursor",
            output_path=Path("/tmp/test"),
            force=True
        )
        assert options.format == "cursor"
        assert options.output_path == Path("/tmp/test")
        assert options.force is True


class TestAgentsCommand:
    """Tests for agents_command."""

    def test_creates_agents_md(self, tmp_path, monkeypatch):
        """Should create AGENTS.md in repo root."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        options = AgentsOptions()
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert "Created" in message
        assert (tmp_path / "AGENTS.md").exists()

    def test_creates_cursorrules(self, tmp_path, monkeypatch):
        """Should create .cursorrules when format=cursor."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        options = AgentsOptions(format="cursor")
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert ".cursorrules" in message
        assert (tmp_path / ".cursorrules").exists()

    def test_creates_both_files(self, tmp_path, monkeypatch):
        """Should create both files when format=all."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        options = AgentsOptions(format="all")
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert (tmp_path / "AGENTS.md").exists()
        assert (tmp_path / ".cursorrules").exists()

    def test_fails_if_exists_without_force(self, tmp_path, monkeypatch):
        """Should fail if AGENTS.md exists and force=False."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / "AGENTS.md").write_text("existing content")

        options = AgentsOptions(force=False)
        exit_code, message = agents_command(options)

        assert exit_code == 1
        assert "already exists" in message
        assert (tmp_path / "AGENTS.md").read_text() == "existing content"

    def test_overwrites_with_force(self, tmp_path, monkeypatch):
        """Should overwrite if force=True."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / "AGENTS.md").write_text("existing content")

        options = AgentsOptions(force=True)
        exit_code, message = agents_command(options)

        assert exit_code == 0
        content = (tmp_path / "AGENTS.md").read_text()
        assert "existing content" not in content
        assert "Generated by" in content

    def test_rejects_path_outside_repo(self, tmp_path, monkeypatch):
        """Should reject output path outside repo root."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        options = AgentsOptions(output_path=tmp_path.parent / "evil.md")
        exit_code, message = agents_command(options)

        assert exit_code == 2
        assert "within repository root" in message


class TestAgentsMdTemplate:
    """Tests for AGENTS.md template content."""

    def test_template_has_quick_reference(self, tmp_path, monkeypatch):
        """Template should have quick reference table."""
        monkeypatch.chdir(tmp_path)
        content = _generate_agents_md(tmp_path)

        assert "## Quick Reference" in content
        assert "ontos map" in content
        assert "ontos agents" in content
        assert "ontos doctor" in content
        assert "ontos log" in content
        assert "ontos query" in content

    def test_template_has_project_stats(self, tmp_path, monkeypatch):
        """Template should have project stats section."""
        monkeypatch.chdir(tmp_path)
        content = _generate_agents_md(tmp_path)

        assert "## Project Stats" in content
        assert "Documents:" in content
        assert "Last context map update:" in content

    def test_template_has_staleness_warning(self, tmp_path, monkeypatch):
        """Template should have staleness warning."""
        monkeypatch.chdir(tmp_path)
        content = _generate_agents_md(tmp_path)

        assert "stale" in content.lower()


class TestCursorrulesTemplate:
    """Tests for .cursorrules template content."""

    def test_template_has_commands(self, tmp_path, monkeypatch):
        """Template should list key commands."""
        monkeypatch.chdir(tmp_path)
        content = _generate_cursorrules(tmp_path)

        assert "ontos map" in content
        assert "ontos agents" in content
        assert "ontos doctor" in content


class TestHelperFunctions:
    """Tests for helper functions."""

    def test_get_doc_count_empty(self, tmp_path, monkeypatch):
        """Should return 0 when no docs directory."""
        monkeypatch.chdir(tmp_path)
        count = _get_doc_count(tmp_path)
        assert count == 0

    def test_get_doc_count_with_docs(self, tmp_path, monkeypatch):
        """Should count markdown files in docs directory."""
        monkeypatch.chdir(tmp_path)
        docs = tmp_path / "docs"
        docs.mkdir()
        (docs / "file1.md").write_text("# Doc 1")
        (docs / "file2.md").write_text("# Doc 2")
        (docs / "subdir").mkdir()
        (docs / "subdir" / "file3.md").write_text("# Doc 3")

        count = _get_doc_count(tmp_path)
        assert count == 3

    def test_get_project_name_from_directory(self, tmp_path, monkeypatch):
        """Should use directory name as project name."""
        monkeypatch.chdir(tmp_path)
        name = _get_project_name(tmp_path)
        assert name == tmp_path.name
