"""Tests for agents command (v3.0.0)."""

from pathlib import Path
import sys

import pytest

from ontos.commands.agents import (
    AgentsOptions,
    agents_command,
    find_repo_root,
    generate_agents_content,
    transform_to_cursorrules,
    gather_stats,
)


class TestAgentsOptions:
    """Tests for AgentsOptions dataclass."""

    def test_default_values(self):
        options = AgentsOptions()
        assert options.output_path is None
        assert options.force is False
        assert options.format == "agents"
        assert options.all_formats is False

    def test_with_values(self):
        options = AgentsOptions(
            output_path=Path("/tmp/test.md"),
            force=True,
            format="cursor",
            all_formats=True,
        )
        assert options.output_path == Path("/tmp/test.md")
        assert options.force is True
        assert options.format == "cursor"
        assert options.all_formats is True


class TestAgentsCommand:
    """Tests for agents_command."""

    def test_creates_agents_md(self, tmp_path, monkeypatch):
        """Should create AGENTS.md in repo root."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()

        options = AgentsOptions()
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert "Created" in message
        assert (tmp_path / "AGENTS.md").exists()

    def test_fails_if_exists_without_force(self, tmp_path, monkeypatch):
        """Should fail if AGENTS.md exists and force=False."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / "AGENTS.md").write_text("existing content")

        options = AgentsOptions(force=False)
        exit_code, message = agents_command(options)

        assert exit_code == 1
        assert "already exists" in message
        assert (tmp_path / "AGENTS.md").read_text() == "existing content"

    def test_overwrites_with_force_and_creates_backup(self, tmp_path, monkeypatch):
        """Should overwrite if force=True and create .bak backup."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()
        (tmp_path / "AGENTS.md").write_text("existing content")

        options = AgentsOptions(force=True)
        exit_code, message = agents_command(options)

        assert exit_code == 0
        # Backup should exist
        assert (tmp_path / "AGENTS.md.bak").exists()
        assert (tmp_path / "AGENTS.md.bak").read_text() == "existing content"
        # New content should be different
        assert "Generated by Ontos" in (tmp_path / "AGENTS.md").read_text()

    def test_format_cursor_creates_cursorrules(self, tmp_path, monkeypatch):
        """Should create .cursorrules when format=cursor."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()

        options = AgentsOptions(format="cursor")
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert (tmp_path / ".cursorrules").exists()
        # Should NOT create AGENTS.md when format=cursor
        assert not (tmp_path / "AGENTS.md").exists()

    def test_all_formats_creates_both(self, tmp_path, monkeypatch):
        """Should create both AGENTS.md and .cursorrules when all_formats=True."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()

        options = AgentsOptions(all_formats=True)
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert (tmp_path / "AGENTS.md").exists()
        assert (tmp_path / ".cursorrules").exists()

    def test_rejects_path_outside_repo(self, tmp_path, monkeypatch):
        """Should reject output path outside repo root."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        options = AgentsOptions(output_path=tmp_path.parent / "evil.md")
        exit_code, message = agents_command(options)

        assert exit_code == 2
        assert "within repository root" in message

    def test_rejects_path_traversal_attack(self, tmp_path, monkeypatch):
        """Should reject path traversal attempts like ../../etc/passwd."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")

        # Attempt path traversal
        options = AgentsOptions(output_path=Path("../../etc/passwd"))
        exit_code, message = agents_command(options)

        assert exit_code == 2
        assert "within repository root" in message

    def test_custom_output_path_within_repo(self, tmp_path, monkeypatch):
        """Should allow custom output path within repo."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()
        subdir = tmp_path / "subdir"
        subdir.mkdir()

        options = AgentsOptions(output_path=subdir / "AI_INSTRUCTIONS.md")
        exit_code, message = agents_command(options)

        assert exit_code == 0
        assert (subdir / "AI_INSTRUCTIONS.md").exists()


class TestAgentsContent:
    """Tests for agents content generation."""

    def test_content_has_activation_section(self, tmp_path, monkeypatch):
        """Template should include Ontos Activation section."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        assert "## Ontos Activation" in content
        assert "Tier 1 minimum" in content

    def test_content_has_quick_reference(self, tmp_path, monkeypatch):
        """Template should include Quick Reference with 5 commands."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        assert "## Quick Reference" in content
        assert "ontos map" in content
        assert "ontos agents" in content
        assert "ontos doctor" in content
        assert "ontos log" in content
        assert "ontos query" in content

    def test_content_has_version_and_timestamp(self, tmp_path, monkeypatch):
        """Template should include generation metadata."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        assert "Generated by Ontos v" in content
        assert " UTC" in content

    def test_content_has_project_stats(self, tmp_path, monkeypatch):
        """Template should include project stats."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        assert "## Project Stats" in content
        assert "Doc Count:" in content
        assert "Last Updated:" in content


class TestCursorruleTransform:
    """Tests for .cursorrules transform."""

    def test_title_replaced(self, tmp_path, monkeypatch):
        """Title should be transformed for Cursor."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        transformed = transform_to_cursorrules(content)
        
        assert "# AGENTS.md" not in transformed
        assert "# Ontos Protocol for Cursor" in transformed

    def test_activation_has_trigger(self, tmp_path, monkeypatch):
        """Activation section should have Cursor trigger."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        transformed = transform_to_cursorrules(content)
        
        assert 'When the user says "Ontos"' in transformed
        assert "## Activation" in transformed

    def test_v3_commands_only(self, tmp_path, monkeypatch):
        """Cursorrules should use v3.0 CLI commands only (no v2.x scripts)."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        
        content = generate_agents_content()
        transformed = transform_to_cursorrules(content)
        
        # Should NOT have v2.x script paths
        assert ".ontos/scripts" not in transformed
        assert "python3 .ontos" not in transformed
        # Should have v3.0 CLI commands
        assert "`ontos map`" in transformed
        assert "`ontos agents`" in transformed


class TestFindRepoRoot:
    """Tests for find_repo_root."""

    def test_finds_ontos_toml(self, tmp_path, monkeypatch):
        """Should find directory with .ontos.toml."""
        (tmp_path / ".ontos.toml").write_text("")
        subdir = tmp_path / "a" / "b"
        subdir.mkdir(parents=True)
        monkeypatch.chdir(subdir)

        root = find_repo_root()

        assert root == tmp_path

    def test_finds_git_dir(self, tmp_path, monkeypatch):
        """Should find directory with .git."""
        (tmp_path / ".git").mkdir()
        subdir = tmp_path / "a" / "b"
        subdir.mkdir(parents=True)
        monkeypatch.chdir(subdir)

        root = find_repo_root()

        assert root == tmp_path

    def test_prefers_ontos_toml_over_git(self, tmp_path, monkeypatch):
        """Should prefer .ontos.toml over .git."""
        (tmp_path / ".git").mkdir()
        subdir = tmp_path / "project"
        subdir.mkdir()
        (subdir / ".ontos.toml").write_text("")
        monkeypatch.chdir(subdir)

        root = find_repo_root()

        assert root == subdir


class TestGatherStats:
    """Tests for gather_stats function."""

    def test_counts_md_files(self, tmp_path, monkeypatch):
        """Should count .md files in docs directory."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'\n[paths]\ndocs_dir = '.ontos-internal'")
        docs = tmp_path / ".ontos-internal"
        docs.mkdir()
        (docs / "file1.md").write_text("# Doc 1")
        (docs / "file2.md").write_text("# Doc 2")
        (docs / "file3.md").write_text("# Doc 3")

        stats = gather_stats(tmp_path)
        doc_count = stats["doc_count"]

        assert doc_count == "3"

    def test_returns_unknown_on_error(self, tmp_path, monkeypatch):
        """Should return Unknown if stats gathering fails."""
        monkeypatch.chdir(tmp_path)
        # No .ontos.toml, no docs - should still work with defaults

        stats = gather_stats(tmp_path)
        doc_count = stats["doc_count"]

        # May be Unknown or 0 depending on defaults
        assert doc_count is not None


class TestExportAlias:
    """Tests for deprecated export alias."""

    def test_export_warns_and_delegates(self, tmp_path, monkeypatch, capsys):
        """ontos export should warn and delegate to agents."""
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.0'")
        (tmp_path / ".ontos-internal").mkdir()

        # Import the CLI handler
        from ontos.cli import _cmd_export
        
        # Create mock args
        class MockArgs:
            output = None
            force = False
            json = False
            quiet = False
        
        exit_code = _cmd_export(MockArgs())
        
        captured = capsys.readouterr()
        assert "deprecated" in captured.err.lower()
        assert exit_code == 0
