"""Tests for lenient hook detection in ontos doctor command (Task 5.3).

Tests cover:
- Official marker detection (# ontos-managed-hook)
- Substring detection (ontos hook)
- Python module detection (python3 -m ontos)
- Negative cases (husky, pre-commit framework, empty, binary-like)
"""

import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from ontos.commands.doctor import _is_ontos_hook_lenient


class TestIsOntosHookLenient:
    """Tests for _is_ontos_hook_lenient helper function."""
    
    def test_detects_official_marker(self, tmp_path):
        """Should detect official # ontos-managed-hook marker."""
        hook = tmp_path / "pre-push"
        hook.write_text("""#!/bin/bash
# ontos-managed-hook
python3 -m ontos hook pre-push "$@"
""")
        assert _is_ontos_hook_lenient(hook) is True
    
    def test_detects_ontos_hook_substring(self, tmp_path):
        """Should detect 'ontos hook' substring (case insensitive)."""
        hook = tmp_path / "pre-push"
        hook.write_text("""#!/bin/bash
# Custom script that calls Ontos hook
python3 .ontos/scripts/ontos_hook.py
""")
        assert _is_ontos_hook_lenient(hook) is True
    
    def test_detects_python_module_execution(self, tmp_path):
        """Should detect python3 -m ontos pattern."""
        hook = tmp_path / "pre-push"
        hook.write_text("""#!/bin/bash
# v3.0 style hook
python3 -m ontos hook pre-push "$@"
""")
        assert _is_ontos_hook_lenient(hook) is True
    
    def test_negative_husky_hook(self, tmp_path):
        """Should NOT detect Husky hooks as Ontos-managed."""
        hook = tmp_path / "pre-push"
        hook.write_text("""#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
npm test
""")
        assert _is_ontos_hook_lenient(hook) is False
    
    def test_negative_pre_commit_framework(self, tmp_path):
        """Should NOT detect pre-commit framework hooks as Ontos-managed."""
        hook = tmp_path / "pre-commit"
        hook.write_text("""#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
exec /usr/local/bin/pre-commit run --hook-stage commit "$@"
""")
        assert _is_ontos_hook_lenient(hook) is False
    
    def test_negative_empty_hook(self, tmp_path):
        """Should NOT detect empty hooks as Ontos-managed."""
        hook = tmp_path / "pre-push"
        hook.write_text("")
        assert _is_ontos_hook_lenient(hook) is False
    
    def test_negative_simple_lint_hook(self, tmp_path):
        """Should NOT detect simple lint hooks as Ontos-managed."""
        hook = tmp_path / "pre-commit"
        hook.write_text("""#!/bin/bash
npm run lint
npm run test
""")
        assert _is_ontos_hook_lenient(hook) is False
    
    def test_handles_missing_file(self, tmp_path):
        """Should return False for non-existent file."""
        hook = tmp_path / "does-not-exist"
        assert _is_ontos_hook_lenient(hook) is False
    
    def test_handles_read_error(self, tmp_path):
        """Should return False on read error."""
        hook = tmp_path / "pre-push"
        hook.write_text("content")
        
        with patch.object(Path, 'read_text', side_effect=PermissionError("denied")):
            # Create a real path object to patch
            assert _is_ontos_hook_lenient(hook) is False
    
    def test_case_insensitive_substring(self, tmp_path):
        """Should detect 'ONTOS HOOK' case-insensitively."""
        hook = tmp_path / "pre-push"
        hook.write_text("""#!/bin/bash
# ONTOS HOOK v2 style
python3 .ontos/scripts/hook.py
""")
        assert _is_ontos_hook_lenient(hook) is True
