"""Verification tests for v3.2.1 Activation Resilience features."""

import pytest
from pathlib import Path
from ontos.commands.map import map_command, MapOptions, GenerateMapOptions, generate_context_map
from ontos.commands.agents import agents_command, AgentsOptions, generate_agents_content
from ontos.core.types import DocumentData, DocumentType, DocumentStatus

@pytest.fixture
def mock_docs():
    """Create a set of mock documents for tiered map testing."""
    docs = {}
    
    # Architecture docs (Tier 1)
    docs["arch_1"] = DocumentData(
        id="arch_1",
        filepath=Path("docs/arch_1.md"),
        type=DocumentType.STRATEGY,
        status=DocumentStatus.ACTIVE,
        frontmatter={"summary": "Core strategy doc"},
        content="# Strategy Content",
        depends_on=[]
    )
    docs["ref_1"] = DocumentData(
        id="ref_1",
        filepath=Path("docs/ref_1.md"),
        type=DocumentType.REFERENCE,
        status=DocumentStatus.ACTIVE,
        frontmatter={"summary": "Reference doc"},
        content="# Reference Content",
        depends_on=[]
    )
    
    # Logs (Tier 1)
    for i in range(1, 10):
        log_id = f"log_2026-01-{i:02d}"
        docs[log_id] = DocumentData(
            id=log_id,
            filepath=Path(f"logs/{log_id}.md"),
            type=DocumentType.LOG,
            status=DocumentStatus.ACTIVE,
            frontmatter={"summary": f"Log entry {i}", "date": f"2026-01-{i:02d}"},
            content=f"Log content {i}",
            depends_on=[]
        )
        
    # Atoms (Tier 2 only)
    for i in range(1, 5):
        atom_id = f"atom_{i}"
        docs[atom_id] = DocumentData(
            id=atom_id,
            filepath=Path(f"docs/atoms/{atom_id}.md"),
            type=DocumentType.ATOM,
            status=DocumentStatus.ACTIVE,
            frontmatter={"summary": f"Atom {i}"},
            content=f"Atom content {i}",
            depends_on=[]
        )
        
    return docs

def test_tiered_map_structure(mock_docs):
    """Should generate map with Tier 1 and Tier 2 sections."""
    config = {"project_name": "Test Project", "version": "3.2"}
    options = GenerateMapOptions()
    
    content, _ = generate_context_map(mock_docs, config, options)
    
    # Tier 1 checks
    assert "## Tier 1: Essential Context" in content
    assert "### Project Summary" in content
    assert "### Recent Activity" in content
    
    # Tier 2 checks
    assert "## Tier 2: Document Index" in content
    
    # Tier 3 checks
    assert "## Tier 3: Full Graph Details" in content
    
    # Content frequency
    assert "log_2026-01-09" in content  # Recent log in Tier 1
    assert "arch_1" in content          # Strategy in Tier 1
    assert "atom_1" in content          # Atom in Tier 2 table

def test_agents_user_custom_preservation(tmp_path, monkeypatch):
    """Should preserve <!-- USER CUSTOM --> section in AGENTS.md."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.2'")
    (tmp_path / ".ontos-internal").mkdir()
    
    # 1. Create initial AGENTS.md
    agents_command(AgentsOptions(force=True))
    agents_file = tmp_path / "AGENTS.md"
    assert agents_file.exists()
    
    # 2. Add custom content between markers
    original_content = agents_file.read_text()
    custom_content = "\n## My Rules\n1. Always test.\n"
    new_content = original_content.replace(
        "<!-- USER CUSTOM -->\n<!-- Add your project-specific notes below. This section is preserved during auto-sync. -->\n<!-- /USER CUSTOM -->",
        f"<!-- USER CUSTOM -->{custom_content}<!-- /USER CUSTOM -->"
    )
    agents_file.write_text(new_content)
    
    # 3. Regenerate
    agents_command(AgentsOptions(force=True))
    
    # 4. Verify preservation
    final_content = agents_file.read_text()
    assert "## My Rules" in final_content
    assert "1. Always test." in final_content
    assert "## Staleness" in final_content  # Ensure tail is preserved
    assert "Generated by Ontos" in final_content

def test_map_sync_agents_flag(tmp_path, monkeypatch):
    """Should sync AGENTS.md when --sync-agents is used."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".ontos.toml").write_text("[ontos]\nversion = '3.2'")
    (tmp_path / ".ontos-internal").mkdir()
    (tmp_path / "docs").mkdir()
    
    agents_file = tmp_path / "AGENTS.md"
    # Using old marker to check if we can still detect it? 
    # Actually, the code now looks for <!-- USER CUSTOM -->
    agents_file.write_text("Old Content\n# USER CUSTOM\n<!-- USER CUSTOM -->Old Custom<!-- /USER CUSTOM -->\n## Old Tail")
    
    # Run map --sync-agents
    options = MapOptions(sync_agents=True, quiet=True)
    map_command(options)
    
    # Verify AGENTS.md was updated but preserved custom
    content = agents_file.read_text()
    assert "Generated by Ontos" in content
    assert "Old Custom" in content
    assert "Old Content" not in content
    assert "## Staleness" in content  # New template tail
    assert "## Old Tail" not in content # Old tail should be gone

def test_tier1_token_capping(mock_docs):
    """Tier 1 should be truncated if it exceeds limit (simulated)."""
    # Create very large summary to trigger capping
    large_summary = "A" * 4000
    mock_docs["arch_1"].frontmatter["summary"] = large_summary
    mock_docs["ref_1"].frontmatter["summary"] = large_summary
    
    # Add more logs
    for i in range(10, 20):
        log_id = f"log_large_{i}"
        mock_docs[log_id] = DocumentData(
            id=log_id,
            filepath=Path(f"logs/{log_id}.md"),
            type=DocumentType.LOG,
            status=DocumentStatus.ACTIVE,
            frontmatter={"summary": large_summary},
            content=large_summary,
            depends_on=[]
        )

    config = {"project_name": "Test Project", "version": "3.2"}
    options = GenerateMapOptions()
    
    content, _ = generate_context_map(mock_docs, config, options)
    
    # Check for new truncation message
    assert "Tier 1 truncated to stay within 2k token budget" in content
    assert "Tier 2" in content

def test_tier1_table_escaping(mock_docs):
    """Should escape pipes in Tier 1 tables."""
    # Add a log with a pipe in the summary
    mock_docs["log_pipe"] = DocumentData(
        id="log_pipe",
        filepath=Path("logs/log_pipe.md"),
        type=DocumentType.LOG,
        status=DocumentStatus.ACTIVE,
        frontmatter={"summary": "Fix | Issue #123", "date": "2026-12-30"},
        content="Content",
        depends_on=[]
    )
    
    config = {"project_name": "Test Project", "version": "3.2"}
    options = GenerateMapOptions()
    
    content, _ = generate_context_map(mock_docs, config, options)
    
    # Check for escaped pipe
    assert "Fix \\| Issue #123" in content
