import subprocess
import sys
import os
import warnings
from pathlib import Path
from ontos.commands import consolidate as consolidate_module


CANONICAL_LEDGER_SECTION = (
    "## History Ledger\n\n"
    "| Date | Slug | Event | Decision / Outcome | Impacts | Archive Path |\n"
    "|:---|:---|:---|:---|:---|:---|\n"
)
CANONICAL_HISTORY = f"# Decision History\n\n{CANONICAL_LEDGER_SECTION}"
GENERATED_NARRATIVE_HISTORY = (
    "<!--\n"
    "GENERATED FILE - DO NOT EDIT MANUALLY\n"
    "Regenerated by: legacy history generator\n"
    "-->\n\n"
    "---\n"
    "id: decision_history\n"
    "type: strategy\n"
    "status: active\n"
    "depends_on: []\n"
    "---\n\n"
    "# Decision History\n\n"
    "This file is auto-generated from session logs. Do not edit directly.\n\n"
    "## 2026-01-01\n\n"
    "### [chore] Existing narrative entry\n"
    "- **Log:** `log_existing`\n"
)

def test_consolidate_runtime_root_resolution(tmp_path):
    """Regression test: consolidate must use runtime project root, not package root."""
    # Setup temp project
    project_root = tmp_path / "my_project"
    project_root.mkdir()
    # Create .ontos.toml to mark as project root
    (project_root / ".ontos.toml").write_text("[project]\nname = 'test'\n[paths]\ndocs_dir = 'docs'\nlogs_dir = 'docs/logs'\n")
    
    # Create logs
    logs_dir = project_root / "docs" / "logs"
    logs_dir.mkdir(parents=True)
    (logs_dir / "2020-01-01-test.md").write_text(
        "---\n"
        "id: log_test\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: []\n"
        "---\n"
        "## Goal\n"
        "Test log content\n",
        encoding="utf-8",
    )
    
    # Create decision history in the local project
    strategy_dir = project_root / "docs" / "strategy"
    strategy_dir.mkdir(parents=True)
    history_file = strategy_dir / "decision_history.md"
    history_file.write_text(
        "# Decision History\n\n"
        "## History Ledger\n\n"
        "| Date | Slug | Event | Decision / Outcome | Impacts | Archive Path |\n"
        "|:---|:---|:---|:---|:---|:---|\n",
        encoding="utf-8",
    )

    # Run command via subprocess to ensure it discovers project_root at runtime
    # and doesn't rely on package-anchored PROJECT_ROOT for the command logic.
    env = os.environ.copy()
    env["PYTHONPATH"] = os.getcwd() # Ensure ontos package is findable
    
    result = subprocess.run(
        [sys.executable, "-m", "ontos.cli", "consolidate", "--dry-run", "--all", "--by-age", "--days", "0"],
        cwd=str(project_root),
        capture_output=True,
        text=True,
        env=env
    )

    # Verification
    assert result.returncode == 0
    assert "log_test" in result.stdout
    assert "Would consolidate 1 log(s)" in result.stdout
    # Ensure it didn't crash searching for logs in the package root
    assert "Document load failed" not in result.stderr


def test_consolidate_non_dry_run_updates_history_and_archives(tmp_path):
    """Regression test: non-dry-run consolidate should archive and update history."""
    project_root = tmp_path / "my_project"
    project_root.mkdir()
    (project_root / ".ontos.toml").write_text(
        "[project]\nname = 'test'\n[paths]\ndocs_dir = 'docs'\nlogs_dir = 'docs/logs'\n"
    )

    logs_dir = project_root / "docs" / "logs"
    logs_dir.mkdir(parents=True)
    original_log = logs_dir / "2020-01-01-test.md"
    original_log.write_text(
        "---\n"
        "id: log_test\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: []\n"
        "---\n"
        "## Goal\n"
        "Test log content\n",
        encoding="utf-8",
    )

    strategy_dir = project_root / "docs" / "strategy"
    strategy_dir.mkdir(parents=True)
    history_file = strategy_dir / "decision_history.md"
    history_file.write_text(
        "# Decision History\n\n"
        "## History Ledger\n\n"
        "| Date | Slug | Event | Decision / Outcome | Impacts | Archive Path |\n"
        "|:---|:---|:---|:---|:---|:---|\n",
        encoding="utf-8",
    )

    env = os.environ.copy()
    env["PYTHONPATH"] = os.getcwd()

    result = subprocess.run(
        [sys.executable, "-m", "ontos.cli", "consolidate", "--all", "--by-age", "--days", "0"],
        cwd=str(project_root),
        capture_output=True,
        text=True,
        env=env,
    )

    archived_log = project_root / "docs" / "archive" / "logs" / "2020-01-01-test.md"
    assert result.returncode == 0
    assert "Consolidated 1 log(s)." in result.stdout
    assert archived_log.exists()
    assert not original_log.exists()
    assert (
        "| 2020-01-01 | test | chore | Test log content | — | `docs/archive/logs/2020-01-01-test.md` |"
        in history_file.read_text(encoding="utf-8")
    )
    assert "Error archiving" not in result.stderr


def test_consolidate_warns_on_legacy_user_layout_fallbacks(tmp_path, monkeypatch):
    """Consolidate should warn when falling back to pre-v2.5.2 user layouts."""
    project_root = tmp_path / "legacy_project"
    project_root.mkdir()
    (project_root / ".ontos.toml").write_text(
        "[project]\nname = 'test'\n[paths]\ndocs_dir = 'docs'\nlogs_dir = 'docs/logs'\n"
    )

    logs_dir = project_root / "docs" / "logs"
    logs_dir.mkdir(parents=True)
    (logs_dir / "2020-01-01-test.md").write_text(
        "---\n"
        "id: log_test\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: []\n"
        "---\n"
        "## Goal\n"
        "Test log content\n",
        encoding="utf-8",
    )

    # Legacy layouts present, new layouts absent.
    (project_root / "docs" / "archive").mkdir(parents=True)
    (project_root / "docs" / "decision_history.md").write_text(
        "# Decision History\n\n"
        "## History Ledger\n\n"
        "| Date | Slug | Event | Decision / Outcome | Impacts | Archive Path |\n"
        "|:---|:---|:---|:---|:---|:---|\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(project_root)
    from ontos.core import paths as paths_module
    paths_module._deprecation_warned.clear()
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        exit_code, _ = consolidate_module._run_consolidate_command(
            consolidate_module.ConsolidateOptions(
                by_age=True,
                days=0,
                dry_run=True,
                all=True,
                quiet=True,
            )
        )

    warning_messages = [str(w.message) for w in caught]
    assert exit_code == 0
    assert any("deprecated path 'docs/archive/'" in m for m in warning_messages)
    assert any("deprecated path 'docs/decision_history.md'" in m for m in warning_messages)


def _write_user_project(
    tmp_path: Path,
    *,
    retention_count: int = 20,
    create_history: bool = True,
    history_content: str = CANONICAL_HISTORY,
) -> Path:
    project_root = tmp_path / "project"
    project_root.mkdir()
    (project_root / ".ontos.toml").write_text(
        "[project]\n"
        "name = 'test'\n"
        "[paths]\n"
        "docs_dir = 'docs'\n"
        "logs_dir = 'docs/logs'\n"
        "[workflow]\n"
        f"log_retention_count = {retention_count}\n",
        encoding="utf-8",
    )
    (project_root / "docs" / "logs").mkdir(parents=True)
    history_file = project_root / "docs" / "strategy" / "decision_history.md"
    if create_history:
        history_file.parent.mkdir(parents=True)
        history_file.write_text(history_content, encoding="utf-8")
    return project_root


def _write_log(
    project_root: Path,
    day: int,
    *,
    logs_dir=None,
    goal=None,
) -> Path:
    target_dir = logs_dir or project_root / "docs" / "logs"
    target_dir.mkdir(parents=True, exist_ok=True)
    slug = f"log-{day:02d}"
    path = target_dir / f"2020-01-{day:02d}-{slug}.md"
    path.write_text(
        "---\n"
        f"id: log_{day:02d}\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: []\n"
        "---\n"
        "## Goal\n"
        f"{goal or f'Goal {day}'}\n",
        encoding="utf-8",
    )
    return path


def test_consolidate_rejects_count_zero(tmp_path, monkeypatch):
    project_root = _write_user_project(tmp_path)
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(count=0, by_age=False, dry_run=True, all=True, quiet=True)
    )

    assert exit_code == 2
    assert "count must be >= 1" in message


def test_consolidate_append_failure_does_not_move_log(tmp_path, monkeypatch):
    project_root = _write_user_project(tmp_path)
    log_path = project_root / "docs" / "logs" / "2020-01-01-broken.md"
    log_path.write_text(
        "---\n"
        "id: log_broken\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: []\n"
        "---\n"
        "## Goal\n"
        "Broken\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(project_root)
    monkeypatch.setattr(consolidate_module, "append_to_decision_history", lambda *args, **kwargs: False)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(by_age=True, days=0, dry_run=False, all=True, quiet=True)
    )

    assert exit_code == 5
    assert "failures" in message
    assert log_path.exists()
    assert not (project_root / "docs" / "archive" / "logs" / log_path.name).exists()


def test_consolidate_commit_failure_reports_partial_results(tmp_path, monkeypatch):
    project_root = _write_user_project(tmp_path)
    (project_root / "docs" / "logs" / "2020-01-01-a.md").write_text(
        "---\nid: log_a\ntype: log\nevent_type: chore\nimpacts: []\n---\n## Goal\nA\n",
        encoding="utf-8",
    )
    (project_root / "docs" / "logs" / "2020-01-02-b.md").write_text(
        "---\nid: log_b\ntype: log\nevent_type: chore\nimpacts: []\n---\n## Goal\nB\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(project_root)
    original_commit = consolidate_module.SessionContext.commit
    commit_calls = {"count": 0}

    def _flaky_commit(self):
        commit_calls["count"] += 1
        if commit_calls["count"] == 1:
            raise RuntimeError("simulated commit failure")
        return original_commit(self)

    monkeypatch.setattr(consolidate_module.SessionContext, "commit", _flaky_commit)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(by_age=True, days=0, dry_run=False, all=True, quiet=True)
    )

    assert exit_code == 5
    assert "1 failures" in message
    archived_logs = list((project_root / "docs" / "archive" / "logs").glob("*.md"))
    remaining_logs = list((project_root / "docs" / "logs").glob("*.md"))
    assert len(archived_logs) == 1
    assert len(remaining_logs) == 1


def test_consolidate_normalizes_scalar_impacts(tmp_path, monkeypatch):
    project_root = _write_user_project(tmp_path)
    log_path = project_root / "docs" / "logs" / "2020-01-01-impacts.md"
    log_path.write_text(
        "---\n"
        "id: log_impacts\n"
        "type: log\n"
        "event_type: chore\n"
        "impacts: foo\n"
        "---\n"
        "## Goal\n"
        "Scalar impacts test\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(project_root)

    exit_code, _ = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(by_age=True, days=0, dry_run=False, all=True, quiet=True)
    )

    history = (project_root / "docs" / "strategy" / "decision_history.md").read_text(encoding="utf-8")
    assert exit_code == 0
    assert "| foo |" in history
    assert "f, o, o" not in history


def test_consolidate_omitted_count_loads_user_workflow_retention(
    tmp_path, monkeypatch
):
    project_root = _write_user_project(tmp_path, retention_count=2)
    for day in range(1, 6):
        _write_log(project_root, day)
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            count=None,
            dry_run=True,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 0
    assert message == "Would consolidate 3 logs"


def test_consolidate_explicit_count_overrides_user_workflow_retention(
    tmp_path, monkeypatch
):
    project_root = _write_user_project(tmp_path, retention_count=1)
    for day in range(1, 6):
        _write_log(project_root, day)
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            count=3,
            dry_run=True,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 0
    assert message == "Would consolidate 2 logs"


def test_consolidate_contributor_mode_uses_default_retention_not_repo_config(
    tmp_path, monkeypatch
):
    project_root = _write_user_project(tmp_path, retention_count=1)
    contributor_logs = project_root / ".ontos-internal" / "logs"
    for day in range(1, 23):
        _write_log(project_root, day, logs_dir=contributor_logs)
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            count=None,
            dry_run=True,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 0
    assert message == "Would consolidate 2 logs"


def test_consolidate_by_age_is_independent_of_count_validation(tmp_path, monkeypatch):
    project_root = _write_user_project(tmp_path, retention_count=2)
    _write_log(project_root, 1)
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            count=0,
            by_age=True,
            days=0,
            dry_run=True,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 0
    assert message == "Would consolidate 1 logs"


def test_consolidate_initializes_missing_user_history_with_canonical_ledger(
    tmp_path, monkeypatch
):
    project_root = _write_user_project(tmp_path, create_history=False)
    source = _write_log(project_root, 1, goal="Initialize missing history")
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    archived_path = project_root / "docs" / "archive" / "logs" / source.name
    history = history_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert message == "Consolidated 1 logs"
    assert not source.exists()
    assert archived_path.exists()
    assert history.startswith("---\nid: decision_history\n")
    assert history.count(CANONICAL_LEDGER_SECTION) == 1
    assert f"`docs/archive/logs/{source.name}`" in history


def test_consolidate_self_heals_generated_narrative_preserving_prefix(
    tmp_path, monkeypatch
):
    project_root = _write_user_project(
        tmp_path,
        history_content=GENERATED_NARRATIVE_HISTORY,
    )
    source = _write_log(project_root, 1, goal="Preserve narrative")
    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    original = history_path.read_bytes()
    monkeypatch.chdir(project_root)

    exit_code, _ = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    updated = history_path.read_bytes()
    assert exit_code == 0
    assert updated[: len(original)] == original
    assert updated.decode("utf-8").count(CANONICAL_LEDGER_SECTION) == 1
    assert f"`docs/archive/logs/{source.name}`" in updated.decode("utf-8")


def test_consolidate_self_heal_preserves_crlf_narrative_bytes(
    tmp_path, monkeypatch
):
    crlf_history = GENERATED_NARRATIVE_HISTORY.replace("\n", "\r\n")
    project_root = _write_user_project(
        tmp_path,
        history_content="",
    )
    source = _write_log(project_root, 1, goal="Preserve CRLF narrative")
    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    original = crlf_history.encode("utf-8")
    history_path.write_bytes(original)
    monkeypatch.chdir(project_root)

    exit_code, _ = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    updated = history_path.read_bytes()
    assert exit_code == 0
    assert updated.startswith(original)
    assert updated[: len(original)].count(b"\r\n") == original.count(b"\r\n")
    assert f"`docs/archive/logs/{source.name}`".encode() in updated


def test_consolidate_arbitrary_history_fails_closed_without_moves(
    tmp_path, monkeypatch
):
    arbitrary_history = "# Personal notes\n\nThis is not an Ontos history file.\n"
    project_root = _write_user_project(
        tmp_path,
        history_content=arbitrary_history,
    )
    source = _write_log(project_root, 1)
    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 5
    assert message == "Consolidated 0 logs with 1 failures"
    assert source.exists()
    assert not (project_root / "docs" / "archive" / "logs" / source.name).exists()
    assert history_path.read_text(encoding="utf-8") == arbitrary_history


def test_consolidate_malformed_existing_ledger_fails_closed_without_moves(
    tmp_path, monkeypatch
):
    malformed_history = (
        "---\nid: decision_history\ntype: strategy\n---\n\n"
        "# Decision History\n\n"
        "## History Ledger\n\n"
        "| Date | Outcome |\n"
        "|:---|:---|\n"
    )
    project_root = _write_user_project(
        tmp_path,
        history_content=malformed_history,
    )
    source = _write_log(project_root, 1)
    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    assert exit_code == 5
    assert message == "Consolidated 0 logs with 1 failures"
    assert source.exists()
    assert not (project_root / "docs" / "archive" / "logs" / source.name).exists()
    assert history_path.read_text(encoding="utf-8") == malformed_history


def test_consolidate_multiple_logs_adds_exactly_one_ledger(tmp_path, monkeypatch):
    project_root = _write_user_project(
        tmp_path,
        history_content=GENERATED_NARRATIVE_HISTORY,
    )
    sources = [_write_log(project_root, day) for day in (1, 2)]
    monkeypatch.chdir(project_root)

    exit_code, message = consolidate_module._run_consolidate_command(
        consolidate_module.ConsolidateOptions(
            by_age=True,
            days=0,
            all=True,
            quiet=True,
        )
    )

    history = (
        project_root / "docs" / "strategy" / "decision_history.md"
    ).read_text(encoding="utf-8")
    assert exit_code == 0
    assert message == "Consolidated 2 logs"
    assert history.count(CANONICAL_LEDGER_SECTION) == 1
    assert history.count("## History Ledger") == 1
    for source in sources:
        assert f"`docs/archive/logs/{source.name}`" in history


def test_append_to_decision_history_is_idempotent_for_archive_path(tmp_path):
    project_root = _write_user_project(tmp_path)
    history_path = project_root / "docs" / "strategy" / "decision_history.md"
    archive_path = "docs/archive/logs/2020-01-01-repeat.md"

    first_context = consolidate_module.SessionContext.from_repo(project_root)
    assert consolidate_module.append_to_decision_history(
        "2020-01-01",
        "repeat",
        "chore",
        "First summary",
        [],
        archive_path,
        history_path,
        first_context,
        consolidate_module.OutputHandler(quiet=True),
    )
    first_context.commit()
    first_content = history_path.read_text(encoding="utf-8")

    second_context = consolidate_module.SessionContext.from_repo(project_root)
    assert consolidate_module.append_to_decision_history(
        "2020-01-01",
        "repeat",
        "chore",
        "Replacement summary",
        [],
        archive_path,
        history_path,
        second_context,
        consolidate_module.OutputHandler(quiet=True),
    )
    assert second_context.commit() == []

    assert history_path.read_text(encoding="utf-8") == first_content
    assert first_content.count(f"`{archive_path}`") == 1
    assert "First summary" in first_content
    assert "Replacement summary" not in first_content


def test_tracked_decision_history_template_uses_exact_canonical_ledger():
    repository_root = Path(__file__).resolve().parents[2]
    template = (
        repository_root / ".ontos" / "templates" / "decision_history_template.md"
    ).read_text(encoding="utf-8")

    assert template.count(CANONICAL_LEDGER_SECTION) == 1
