"""Shared instruction-artifact generation helpers.

This module centralizes generation logic for:
- AGENTS.md
- .cursorrules
- CLAUDE.md
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional, Tuple

import ontos
from ontos.core.instruction_protocol import (
    InstructionProtocolConfig,
    preserve_user_custom_section,
    render_activation_protocol_head,
    render_activation_protocol_tail,
    render_trigger_phrases,
)
from ontos.core.claude_template import generate_claude_content


@dataclass(frozen=True)
class InstructionArtifactResult:
    """Result payload for one generated artifact."""

    path: str
    created: bool
    message: str


AGENTS_PROTOCOL_CONFIG = InstructionProtocolConfig(
    instruction_file="AGENTS.md",
    regenerate_command="ontos agents",
    regenerate_purpose="Generate instruction files",
    staleness_command="ontos map --sync-agents",
    map_sync_command="ontos map --sync-agents",
    map_sync_purpose="Regenerate map + sync AGENTS.md",
)

AGENTS_HEADER_TEMPLATE = """# AGENTS.md

This project uses **Ontos** for documentation management.

Generated by Ontos v{ontos_version} on {generated_at}"""

AGENTS_CURRENT_PROJECT_STATE_TEMPLATE = """## Current Project State

> Auto-synced: {generated_at}

| Metric | Value |
|--------|-------|
| Branch | {current_branch} |
| Doc Count | {doc_count} |
| Last Log | {last_log} |
| Health | {health_summary} |"""

AGENTS_PROJECT_STATS_TEMPLATE = """## Project Stats
- Doc Count: {doc_count}
- Last Updated: {last_updated}"""

AGENTS_MCP_WRITE_TOOLS_TEMPLATE = """## MCP Write Tools

When the server runs without `--read-only`, MCP may expose:
- `scaffold_document`
- `log_session`
- `session_end`
- `promote_document`
- `rename_document`

Write-tool contracts:
- `read_only=True` omits the write tools from discovery.
- `workspace_id` is optional and defaults to the served workspace.
- `session_end` is the typed session archive wrapper for Goal, Key Decisions,
  Alternatives Considered, Impacts, and Testing.
- `rename_document` always uses library scope.
"""


def find_repo_root() -> Optional[Path]:
    """Find the repository root using Ontos and git markers."""
    current = Path.cwd()

    for parent in [current] + list(current.parents):
        if (parent / ".ontos.toml").exists():
            return parent

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    for parent in [current] + list(current.parents):
        if (parent / ".git").exists():
            return parent

    return None


def gather_stats(repo_root: Path, scope: Optional[str] = None) -> Dict[str, str]:
    """Gather project stats for instruction templates."""
    stats = {
        "doc_count": "Unknown",
        "last_updated": "Unknown",
        "current_branch": "Unknown",
        "last_log": "None",
        "health_summary": "Unknown",
    }

    try:
        config_path = repo_root / ".ontos.toml"
        docs_dir = repo_root / "docs"
        logs_dir = repo_root / "docs" / "logs"
        context_map = repo_root / "Ontos_Context_Map.md"

        skip_patterns = []
        doc_paths = []
        if config_path.exists():
            try:
                from ontos.io.config import load_project_config
                from ontos.io.scan_scope import collect_scoped_documents, resolve_scan_scope

                config = load_project_config(repo_root=repo_root)
                docs_dir = repo_root / config.paths.docs_dir
                logs_dir = repo_root / config.paths.logs_dir
                context_map = repo_root / config.paths.context_map
                skip_patterns = config.scanning.skip_patterns

                effective_scope = resolve_scan_scope(scope, config.scanning.default_scope)
                doc_paths = collect_scoped_documents(
                    repo_root,
                    config,
                    effective_scope,
                    base_skip_patterns=skip_patterns,
                )
            except Exception:
                doc_paths = []

        if not doc_paths and docs_dir.exists():
            from ontos.io.files import scan_documents

            doc_paths = scan_documents([docs_dir], skip_patterns=skip_patterns)

        count = len(doc_paths)
        stats["doc_count"] = "5000+" if count >= 5000 else str(count)

        mtimes = []
        for path in [context_map, config_path]:
            if path.exists():
                mtimes.append(path.stat().st_mtime)

        if logs_dir.exists():
            for log_file in logs_dir.glob("*.md"):
                mtimes.append(log_file.stat().st_mtime)

        if mtimes:
            max_mtime = max(mtimes)
            dt = datetime.fromtimestamp(max_mtime, tz=timezone.utc)
            stats["last_updated"] = dt.strftime("%Y-%m-%d %H:%M:%S UTC")

        try:
            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=repo_root,
            )
            if result.returncode == 0:
                stats["current_branch"] = result.stdout.strip()
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

        if logs_dir.exists():
            log_files = sorted(logs_dir.glob("*.md"), reverse=True)
            if log_files:
                stats["last_log"] = log_files[0].stem

        stats["health_summary"] = "✓ Map exists" if context_map.exists() else "⚠ No map"
    except Exception:
        pass

    return stats


def generate_agents_content(existing_content: Optional[str] = None, scope: Optional[str] = None) -> str:
    """Generate AGENTS.md content with project stats."""
    repo_root = find_repo_root()
    stats = gather_stats(repo_root, scope=scope) if repo_root else gather_stats(Path.cwd(), scope=scope)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header = AGENTS_HEADER_TEMPLATE.format(
        ontos_version=ontos.__version__,
        generated_at=generated_at,
    )

    current_project_state = AGENTS_CURRENT_PROJECT_STATE_TEMPLATE.format(
        generated_at=generated_at,
        current_branch=stats["current_branch"],
        doc_count=stats["doc_count"],
        last_log=stats["last_log"],
        health_summary=stats["health_summary"],
    )

    trigger_phrases = render_trigger_phrases()
    activation_head = render_activation_protocol_head(AGENTS_PROTOCOL_CONFIG)
    project_stats = AGENTS_PROJECT_STATS_TEMPLATE.format(
        doc_count=stats["doc_count"],
        last_updated=stats["last_updated"],
    )
    mcp_write_tools = AGENTS_MCP_WRITE_TOOLS_TEMPLATE
    activation_tail = render_activation_protocol_tail(AGENTS_PROTOCOL_CONFIG)

    content = "\n\n".join(
        [
            header,
            trigger_phrases,
            current_project_state,
            activation_head,
            project_stats,
            mcp_write_tools,
            activation_tail,
        ]
    ) + "\n"

    return preserve_user_custom_section(content, existing_content)


def transform_to_cursorrules(agents_content: str) -> str:
    """Transform AGENTS.md content to .cursorrules format."""
    lines = agents_content.split("\n")
    result = []
    skip_until_next_section = False
    in_user_custom = False

    for line in lines:
        if line == "<!-- USER CUSTOM -->":
            in_user_custom = True
            result.append(line)
            continue

        if in_user_custom:
            result.append(line)
            if line == "<!-- /USER CUSTOM -->":
                in_user_custom = False
            continue

        if line.startswith("# AGENTS.md"):
            result.append("# Ontos Protocol for Cursor")
            continue

        if line.startswith("## "):
            section_name = line[3:].strip()
            skip_until_next_section = False

            if section_name == "Ontos Activation":
                result.append("")
                result.append('When the user says "Ontos" or "Activate Ontos":')
                result.append("")
                result.append("## Activation")
                continue
            if section_name == "Session End":
                result.append("")
                result.append("When ending a session:")
                result.append("")
                result.append("## Session End")
                continue
            if section_name in (
                "Trigger Phrases",
                "Re-Activation Trigger",
                "After Context Compaction (/compact)",
                "Quick Reference",
                "MCP Write Tools",
                "Project Stats",
                "Core Invariants",
                "Staleness",
            ):
                result.append(line)
                continue

            skip_until_next_section = True
            continue

        if skip_until_next_section:
            continue
        result.append(line)

    return "\n".join(result)


_GENERATED_HEADER_TIMESTAMP_RE = re.compile(
    r"^(Generated by Ontos v.+ on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC$"
)
_GENERATED_BY_ONTOS_RE = re.compile(r"^Generated by Ontos v", re.MULTILINE)
_USER_CUSTOM_MARKER = "<!-- USER CUSTOM -->"

# (#173) Ownership classes for instruction files. Only `ontos_owned` files
# may be regenerated implicitly (maintain sync task, map --sync-agents);
# everything else requires an explicit `ontos agents --force`.
OWNERSHIP_ONTOS_OWNED = "ontos_owned"
OWNERSHIP_MANAGED_BLOCK = "managed_block"
OWNERSHIP_USER_MANAGED = "user_managed"
OWNERSHIP_MISSING = "missing"


def classify_instruction_ownership(path: Path) -> str:
    """(#173) Classify who owns an instruction file.

    Returns one of:
    - ``ontos_owned``: carries the ``Generated by Ontos v…`` header — the
      whole file is an Ontos-generated artifact (its USER CUSTOM section is
      preserved on regeneration).
    - ``managed_block``: no generation header, but contains USER CUSTOM
      markers — a hand-maintained file that embeds Ontos-managed content.
    - ``user_managed``: neither marker — Ontos did not write this file and
      must never overwrite it implicitly.
    - ``missing``: the file does not exist.

    Unreadable files classify as ``user_managed`` (fail closed: when
    ownership cannot be proven, Ontos does not own it).
    """
    if not path.exists():
        return OWNERSHIP_MISSING
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return OWNERSHIP_USER_MANAGED
    if _GENERATED_BY_ONTOS_RE.search(content):
        return OWNERSHIP_ONTOS_OWNED
    if _USER_CUSTOM_MARKER in content:
        return OWNERSHIP_MANAGED_BLOCK
    return OWNERSHIP_USER_MANAGED


def is_agents_semantically_stale(
    repo_root: Path,
    scope: Optional[str] = None,
) -> bool:
    """(#173) Decide AGENTS.md staleness by content, not mtime.

    Renders the content Ontos would write right now (preserving the existing
    USER CUSTOM section) and compares it against the file through the
    timestamp-normalizing semantic comparator. Two checkouts of the same
    tree therefore agree on freshness regardless of checkout write order,
    clone time, or touch-only changes — the mtime signal was reproducibly
    wrong across clones and worktrees.

    Raises whatever ``generate_agents_content`` raises; callers surface the
    failure instead of guessing.
    """
    agents_path = repo_root / "AGENTS.md"
    existing = agents_path.read_text(encoding="utf-8")
    expected = generate_agents_content(existing, scope=scope)
    return _without_generated_instruction_timestamps(
        existing
    ) != _without_generated_instruction_timestamps(expected)
_AUTO_SYNC_TIMESTAMP_RE = re.compile(
    r"^> Auto-synced: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC$"
)
_LAST_UPDATED_TIMESTAMP_RE = re.compile(
    r"^- Last Updated: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC$"
)


def _without_generated_instruction_timestamps(content: str) -> str:
    """Normalize volatile instruction timestamps for semantic comparison."""
    normalized = []
    for line in content.splitlines(keepends=True):
        ending = "\n" if line.endswith("\n") else ""
        value = line[:-1] if ending else line

        header_match = _GENERATED_HEADER_TIMESTAMP_RE.fullmatch(value)
        if header_match:
            value = f"{header_match.group(1)}<generated>"
        elif _AUTO_SYNC_TIMESTAMP_RE.fullmatch(value):
            value = "> Auto-synced: <generated>"
        elif _LAST_UPDATED_TIMESTAMP_RE.fullmatch(value):
            value = "- Last Updated: <generated>"

        normalized.append(value + ending)
    return "".join(normalized)


def create_backup(path: Path) -> None:
    """Create a `.bak` backup if file exists."""
    if path.exists():
        backup_path = path.with_suffix(path.suffix + ".bak")
        backup_path.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")


def _write_instruction_artifact_if_changed(
    path: Path,
    content: str,
    *,
    backup_on_change: bool = False,
) -> bool:
    """Write an instruction artifact only when meaningful content changed.

    (#173) The historical ``touch_on_unchanged`` hook — touching the file to
    game the old mtime staleness signal — is retired with that signal;
    staleness is now decided by content via
    :func:`is_agents_semantically_stale`.
    """
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if (
            _without_generated_instruction_timestamps(existing)
            == _without_generated_instruction_timestamps(content)
        ):
            return False
        if backup_on_change:
            create_backup(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def generate_agents_files(
    *,
    repo_root: Path,
    output_path: Optional[Path] = None,
    force: bool = False,
    format: str = "agents",
    all_formats: bool = False,
    scope: Optional[str] = None,
) -> Tuple[int, str]:
    """Generate AGENTS.md and/or .cursorrules."""
    messages = []
    generate_agents = format == "agents" or all_formats
    generate_cursor = format == "cursor" or all_formats

    if generate_agents:
        agents_path = output_path or repo_root / "AGENTS.md"
        try:
            agents_path.resolve().relative_to(repo_root.resolve())
        except ValueError:
            return 2, f"Error: Output path must be within repository root ({repo_root})"

        if agents_path.exists() and not force:
            return 2, f"AGENTS.md already exists at {agents_path}. Use --force to overwrite."

        try:
            existed = agents_path.exists()
            existing_content = (
                agents_path.read_text(encoding="utf-8")
                if existed
                else None
            )
            agents_content = generate_agents_content(existing_content, scope=scope)
            changed = _write_instruction_artifact_if_changed(
                agents_path,
                agents_content,
                backup_on_change=force,
            )
            action = (
                "Unchanged" if not changed else ("Updated" if existed else "Created")
            )
            messages.append(f"{action} {agents_path}")
        except Exception as exc:
            return 5, f"Error writing AGENTS.md: {exc}"

    if generate_cursor:
        cursor_path = repo_root / ".cursorrules"
        if cursor_path.exists() and not force:
            if generate_agents:
                messages.append(".cursorrules already exists. Use --force to overwrite.")
            else:
                return 2, f".cursorrules already exists at {cursor_path}. Use --force to overwrite."
        else:
            try:
                existed = cursor_path.exists()
                existing_cursor_content = (
                    cursor_path.read_text(encoding="utf-8") if existed else None
                )
                existing_agents_path = repo_root / "AGENTS.md"
                existing_content = (
                    existing_agents_path.read_text(encoding="utf-8")
                    if existing_agents_path.exists()
                    else None
                )
                agents_content = generate_agents_content(existing_content, scope=scope)
                cursor_content = transform_to_cursorrules(agents_content)
                cursor_content = preserve_user_custom_section(
                    cursor_content,
                    existing_cursor_content,
                )
                changed = _write_instruction_artifact_if_changed(
                    cursor_path,
                    cursor_content,
                    backup_on_change=force,
                )
                action = (
                    "Unchanged"
                    if not changed
                    else ("Updated" if existed else "Created")
                )
                messages.append(f"{action} {cursor_path}")
            except Exception as exc:
                return 5, f"Error writing .cursorrules: {exc}"

    return 0, "\n".join(messages) if messages else "No files generated"


def generate_claude_file(
    *,
    repo_root: Path,
    output_path: Optional[Path] = None,
    force: bool = False,
) -> Tuple[int, str]:
    """Generate CLAUDE.md."""
    path = output_path or repo_root / "CLAUDE.md"

    try:
        resolved_output = path.resolve()
        resolved_root = repo_root.resolve()
        if (repo_root / ".git").exists() or (repo_root / ".ontos.toml").exists():
            resolved_output.relative_to(resolved_root)
    except ValueError:
        return 2, f"Error: Output path must be within repository root ({repo_root})"

    if path.exists() and not force:
        return 2, f"CLAUDE.md already exists at {path}. Use --force to overwrite."

    try:
        existed = path.exists()
        existing_content = path.read_text(encoding="utf-8") if existed else None
        changed = _write_instruction_artifact_if_changed(
            path,
            generate_claude_content(existing_content),
        )
    except (IOError, OSError) as exc:
        return 5, f"Error writing file to {path}: {exc}"
    except Exception as exc:
        return 5, f"An unexpected error occurred: {exc}"

    action = "Unchanged" if not changed else ("Updated" if existed else "Created")
    return 0, f"{action} {path}"


def generate_all_instruction_exports(
    *,
    repo_root: Path,
    force: bool = False,
    scope: Optional[str] = None,
) -> Tuple[int, Dict[str, InstructionArtifactResult]]:
    """Generate AGENTS.md, .cursorrules, and CLAUDE.md in one operation."""
    results: Dict[str, InstructionArtifactResult] = {}
    agents_bundle_missing = any(
        not path.exists()
        for path in (repo_root / "AGENTS.md", repo_root / ".cursorrules")
    )
    claude_missing = not (repo_root / "CLAUDE.md").exists()

    agents_code, agents_message = generate_agents_files(
        repo_root=repo_root,
        force=force,
        all_formats=True,
        scope=scope,
    )
    results["agents_bundle"] = InstructionArtifactResult(
        path=str(repo_root),
        created=agents_code == 0 and agents_bundle_missing,
        message=agents_message,
    )

    claude_code, claude_message = generate_claude_file(
        repo_root=repo_root,
        force=force,
    )
    results["claude"] = InstructionArtifactResult(
        path=str(repo_root / "CLAUDE.md"),
        created=claude_code == 0 and claude_missing,
        message=claude_message,
    )

    if agents_code == 0 and claude_code == 0:
        exit_code = 0
    elif 5 in {agents_code, claude_code}:
        exit_code = 5
    else:
        exit_code = 2
    return exit_code, results
